### ISSUE TITLE
Server won't boot & wont produce crash report

### ISSUE THREAD

**Issue by Omega-The-III** [AbdElAziz333/Canary#43]
I'm using the latest version of canary on forge 1.19.2 43.1.47.
This one seems like another issue that is already posted but the logs are different and this only happens on server, not on the client.

canary-mc1.19.2-0.0.10

### Reproduction Steps

Step 1: use this modpack in a forge 1.19.2 43.1.47 server.
[Omega's Create & Vanilla+-1.0.1.zip](https://github.com/AbdElAziz333/Canary/files/9973345/Omega.s.Create.Vanilla%2B-1.0.1.zip)
step 2: take out the client mods, entity culling, legendary tooltip ect.
step 3. launch and watch it crash.

[2022-11-09-14.log.gz](https://github.com/AbdElAziz333/Canary/files/9973368/2022-11-09-14.log.gz)
[debug-5.log.gz](https://github.com/AbdElAziz333/Canary/files/9973369/debug-5.log.gz)

**Comment by Zelioth** [comment]
Same issues on Canary Version 0.0.10

Command states that the server can't start due to the server trying to "Render" a GUI for a client and downgrading or disabling canary fixes this issue. So for some reason in the 0.0.1.0 Update Canary things it's a client side only mod with a GUI or client only based attribute

**Comment by AbdElAziz333** [comment]
fixed in the coming update.
