### ISSUE TITLE
1.19.2 - Forge 43.1.52 - Never Starts Up  ``Failed to Apply Memory Mixins``

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [AbdElAziz333/Canary#55]
This is still an issue. Please leave it open until I have closed it. I promise I won't forget.

https://gist.github.com/P3rf3ctXZer0/d404ad034b5f781a3d4eaf6ef66e0f95

https://github.com/AbdElAziz333/Canary/issues/54

Now crashed with 
canary-mc1.19.2-0.1.2

Fail point is ``Memory Mixins``

**Comment by AbdElAziz333** [comment]
there a difference between both issues, #54 crashed because i forgot changing the method names to SRG (fixed in 0.1.2), and this one because there a class want to access the private method in Behavior, also i am sorry for closing issues by myself, i close the issues because i am sure it fixed, but if you would like to close it by yourself, then okay!

**Comment by P3rf3ctXZer0** [comment]
I promise I will always close fixed issues as a dev myself I know how important it is to close fixed issues.

**Comment by AbdElAziz333** [comment]
can you test this [build](https://github.com/AbdElAziz333/Canary/releases/tag/mc1.19.2-v0.1.3)?

**Comment by P3rf3ctXZer0** [comment]
Testing now.

**Comment by P3rf3ctXZer0** [comment]
No dice https://gist.github.com/P3rf3ctXZer0/d824f46f43843a4c22c0a58ae2c19af4

**Comment by AbdElAziz333** [comment]
This issue should be fixed in this new [build](https://github.com/AbdElAziz333/Canary/releases/tag/mc1.19.2-v0.1.3-R)

I hope you have a good day!

**Comment by P3rf3ctXZer0** [comment]
Testing now.

**Comment by P3rf3ctXZer0** [comment]
Success :D
