### ISSUE TITLE
Chunks not loading 1.18.2

### ISSUE THREAD

**Issue by rafalohaki** [AbdElAziz333/Canary#58]
after update from 0.0.9 to 0.0.10, chunks are not loading on the server
after downgrading it to 0.0.9 its working again
using sb3 modpack

**Comment by AbdElAziz333** [comment]
what is sb3 modpack? also can you provide some logs? forge version?

**Comment by rafalohaki** [comment]
sadly i dont have a logs.
stoneblock 3 modpack

**Comment by X-Niter** [comment]
Stoneblock 3 BY the FTB Team. 

forge-1.18.2-40.1.84

Stoneblock 3 version 1.3.0.

0.0.9 is fine until using 0.0.10.

Logs are to no justice due to no error that was seen but I'll provide server and client logs just in case.

[Server Latest Log 1](https://gist.github.com/X-Niter/fc1855ebb70e2cfb0782c6ae1b409d1f)

[Client Latest Log 1](https://gist.github.com/X-Niter/581deaadd8cbc9bdfabce2c1c6e2e424)

Both client and server have identical canary version.

Other users who don't have canary have the same exact issue.

Hope that helps.

**Comment by AbdElAziz333** [comment]
Ok i noticed that Cracker's Wither Storm mod is in sb3, which both have incompatibility and i can't do anything about that because the mod isn't open source. you can add `mixin.ai.nearby_entity_tracking=false` in `canary.properties` and try again until i found a fix this issue.

**Comment by X-Niter** [comment]
Take me with a grain of salt here, but most ARR/Closed Source modes alike are perfectly fine with you patching your own content with a fix so that it runs with theirs, the only real care that each author has ever told me was it's only to control code project copy and re distribution essentially.
I would be very surprised if the author of Wither was that hell-bent and told you "No you can't look at my work to allow yours to work with mine", that has never been seen in my 8 years of Minecraft projects. 

Hope that gives you some motivation XD.

**Comment by AbdElAziz333** [comment]
Don't worry i will try to fix the incompatbility between both Canary and Cracker's Wither Storm mod.

**Comment by DreiPixel** [comment]
> Cracker's Wither Storm mod is in sb3

im pretty sure that mod is not in Stoneblock 3. :V

**Comment by DreiPixel** [comment]
oh and a bit more info. my players have the same problem but I dont have the problem. the difference is that i have canary also installed on my client. the others dont have it

**Comment by X-Niter** [comment]
Trust but didn't verify, my bad.

Looking at the Stoneblock 3 modlist, it would seem that is true.
I have two screenshots showing the Cracker wither storm mod file name and the list of mods starting with 'W' and it is indeed not in there.
![image](https://user-images.githubusercontent.com/30506033/203174836-1f10b5c4-077f-4af7-8d9f-0809c965654a.png)
![image](https://user-images.githubusercontent.com/30506033/203174875-ffc15e57-5dc2-4bc8-a7d3-df504c865f27.png)

**Comment by AbdElAziz333** [comment]
You are correct, then i will look into that by myself.

**Comment by AbdElAziz333** [comment]
should be fixed in the new updates.
[1.19.3](https://www.curseforge.com/minecraft/mc-mods/canary/files/4291690) - [1.19.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4291688) - [1.18.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4291687) .
Good luck!
