### ISSUE TITLE
Hopper won't output in composter

### ISSUE THREAD

**Issue by danielgoeller** [AbdElAziz333/Canary#60]
canary-mc1.19.2-0.0.9 AND canary-mc1.19.2-0.1.3

I try to build a Cactus-Bonemeal-Farm in Better MC 1.19.2 [FORGE] with a hopper, that collects the dropped cactus and outputs it into a composter beneath it.

### Actual Behavior

The hopper faced into a composter beneath it and collects cactus but won't output it into the composter.

### Reproduction Steps

I updated from 0.0.9 to 0.1.3 then restarted MC. After that I replaced all affected blocks several times in different orders. I changed the items in the hopper to bread, wheat and carrots. Still nothing.

After that I turned off Canary, the hoppers instantly started outputting all the cactus. 

So i turned on Canary again and added "mixin.alloc.composter=false" in the config file. After a restart, the hopper still don't want to output the cactus.

Did i miss something in the config file, the mod behaviour or is it a bug?

**Comment by AbdElAziz333** [comment]
This is not issue at all, this is a regular feature from canary for more information press [here](https://github.com/AbdElAziz333/Canary/blob/mc1.19.2/dev/src/main/java/com/abdelaziz/canary/mixin/block/hopper/README.md#how-canary-hoppers-work-different-from-vanilla).
you can disable this feature by adding `mixin.block.hopper=false` in `canary.properties`.

**Comment by aelfwyne** [comment]
How about having the default settings in the config file not break basic vanilla mechanics? That does nothing but cause user frustration.

**Comment by AbdElAziz333** [comment]
I'm sorry i just don't saw you comment, but this issue is fixed in the new versions.
[1.18.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4324082) - [1.19.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4324084) - [1.19.3](https://www.curseforge.com/minecraft/mc-mods/canary/files/4324087)
Once again, I sincerely apologize for not focusing on solving this problem.
I hope you have a good day!
